// <auto-generated />
using System;
using Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aesth.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250806232412_OrdersMigration")]
    partial class OrdersMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aesth.Infrastructure.Persistence.Entities.order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("addressid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("stripe_session_id")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("addressid");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Aesth.Infrastructure.Persistence.Entities.order_address", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<string>("line1")
                        .HasColumnType("text");

                    b.Property<string>("line2")
                        .HasColumnType("text");

                    b.Property<string>("postal_code")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("order_adresses");
                });

            modelBuilder.Entity("Aesth.Infrastructure.Persistence.Entities.order_item", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<Guid?>("orderid")
                        .HasColumnType("uuid");

                    b.Property<long>("price")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<string>("size")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("orderid");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("Aesth.Infrastructure.Persistence.Entities.order", b =>
                {
                    b.HasOne("Aesth.Infrastructure.Persistence.Entities.order_address", "address")
                        .WithMany()
                        .HasForeignKey("addressid");

                    b.Navigation("address");
                });

            modelBuilder.Entity("Aesth.Infrastructure.Persistence.Entities.order_item", b =>
                {
                    b.HasOne("Aesth.Infrastructure.Persistence.Entities.order", null)
                        .WithMany("items")
                        .HasForeignKey("orderid");
                });

            modelBuilder.Entity("Aesth.Infrastructure.Persistence.Entities.order", b =>
                {
                    b.Navigation("items");
                });

#pragma warning restore 612, 618
        }
    }
}
